mqtt:
  enabled: false

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - cat

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 0
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 10
      mode: active_objects
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 10
      mode: active_objects

go2rtc:
  streams:
    cam_2:
      - "ffmpeg:http://192.168.178.154:8080/video#video=h264"

cameras:
  cam_2:
    enabled: true
    friendly_name: Cam 2
    ffmpeg:
      inputs:
        - path: http://192.168.178.154:8080/video
          input_args: preset-http-mjpeg-generic
          roles:
            - detect
            - record
    detect:
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
    live:
      streams:
        Stream 1: cam_2

version: 0.17-0
