mqtt:
  enabled: false

auth:
  enabled: true

objects:
  track:
    - person
    - car
    - bicycle
    - motorcycle
    - dog
    - cat

ffmpeg:
  path: "7.0"

record:
  enabled: true
  continuous:
    days: 0
  motion:
    days: 3
  alerts:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 3
      mode: motion
  detections:
    pre_capture: 5
    post_capture: 5
    retain:
      days: 3
      mode: motion

go2rtc:
  streams:
    cam_2:
      - "ffmpeg:http://192.168.178.154:8080/video#video=h264"

cameras:
  cam_2:
    enabled: true
    friendly_name: Cam 2
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/cam_2
          input_args: preset-rtsp-restream
          roles:
            - detect
            - record
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 5
    record:
      enabled: true
    live:
      streams:
        Stream 1: cam_2

version: 0.17-0
